[theme]
base = "dark"
primaryColor = "#ffffff"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#18181b"
textColor = "#ededed"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
